"""
Write a MeshData object to a CalculiX .inp file.
"""
from __future__ import annotations
from pathlib import Path

from core.mesh_io import MeshData


def write_inp(mesh: MeshData, path: str | Path, title: str = "Crack3D model"):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w") as f:
        f.write(f"** {title}\n")
        f.write("** Generated by Crack3D\n\n")

        # --- Nodes ---
        f.write("*NODE, NSET=NALL\n")
        for nid in sorted(mesh.nodes):
            n = mesh.nodes[nid]
            f.write(f"{nid}, {n.x:.10g}, {n.y:.10g}, {n.z:.10g}\n")

        # --- Elements (grouped by type) ---
        by_type: dict[str, list[int]] = {}
        for eid, el in mesh.elements.items():
            by_type.setdefault(el.etype, []).append(eid)

        for etype, eids in by_type.items():
            f.write(f"\n*ELEMENT, TYPE={etype}, ELSET=EALL\n")
            for eid in sorted(eids):
                nodes = mesh.elements[eid].nodes
                # CalculiX allows max 16 entries per line; wrap if needed
                chunks = [nodes[i:i+15] for i in range(0, len(nodes), 15)]
                first = True
                for chunk in chunks:
                    if first:
                        f.write(f"{eid}, " + ", ".join(map(str, chunk)))
                        first = False
                    else:
                        f.write(",\n" + ", ".join(map(str, chunk)))
                f.write("\n")

        # --- Node sets ---
        for name, ids in mesh.node_sets.items():
            f.write(f"\n*NSET, NSET={name}\n")
            _write_id_list(f, sorted(set(ids)))

        # --- Element sets ---
        for name, ids in mesh.element_sets.items():
            f.write(f"\n*ELSET, ELSET={name}\n")
            _write_id_list(f, sorted(set(ids)))

        # --- Materials ---
        for mat_name, props in mesh.materials.items():
            f.write(f"\n*MATERIAL, NAME={mat_name}\n")
            if "E" in props and "nu" in props:
                f.write("*ELASTIC\n")
                f.write(f"{props['E']:.6g}, {props['nu']:.6g}\n")

        # --- Boundary conditions ---
        if mesh.boundaries:
            f.write("\n*BOUNDARY\n")
            for set_name, dof_vals in mesh.boundaries.items():
                for dof, val in dof_vals:
                    f.write(f"{set_name}, {dof}, {dof}, {val:.10g}\n")

        # --- Concentrated loads ---
        if mesh.cloads:
            f.write("\n*CLOAD\n")
            for set_name, dof_mags in mesh.cloads.items():
                for dof, mag in dof_mags:
                    f.write(f"{set_name}, {dof}, {mag:.10g}\n")


def _write_id_list(f, ids: list[int], per_line: int = 16):
    for i in range(0, len(ids), per_line):
        f.write(", ".join(map(str, ids[i:i + per_line])) + "\n")
